name: Archive dependency

on:
    push:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Archive dependency check reports
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
