name: Build App

on:
    push:
        branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          repository: olive1383/cd
          #tag_with_sha: true
          tags: trivy
            
                  
       
