name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        
        - name: Archive dependency check reports
          uses: actions/upload-artifact@v1
          with:
            name: reports
            path: reports
        - uses: actions/checkout@v2
        - name: Install NPM dependencies
          run: |
            npm install --production --unsafe-perm
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: olive1383/cd
            tag_with_sha: true
            
            
            
            
       