name: Build App

on:
    push:
        branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
    - uses: sburris/dependency-check-action@master
      with:
        Project-Name: TestApp
