name: Trivy

on:
    push:
        branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/<your-username>/<your-image>:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
